version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - "> 3.1.0"
  - dependency-name: husky
    versions:
    - ">= 5.a, < 6"
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint
    versions:
    - 7.23.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
