repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/prettier/prettier
    rev: 1.19.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.7.2
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@6.7.2
          # Parsers
          - babel-eslint@10.0.3
          # Rules
          - eslint-config-airbnb@18.0.1
          - eslint-config-prettier@6.9.0
          # Peer deps for airbnb
          - eslint-plugin-react@7.17.0
          - eslint-plugin-import@2.18.2
          - eslint-plugin-jsx-a11y@6.2.3
          # Plugins
          - eslint-plugin-react-hooks@2.3.0
